export const STYLES = {
	container: {
		position: "relative" as const,
		fontFamily: "var(--font-body)",
		marginBottom: "20px",
	},
	label: {
		display: "block",
		marginBottom: "6px",
		fontSize: "13px",
		fontWeight: 500,
		color: "var(--theme-text)",
	},
	inputRow: {
		display: "flex",
		alignItems: "center",
		border: "1px solid var(--theme-elevation-150)",
		borderRadius: "4px",
		overflow: "hidden" as const,
	},
	input: {
		flex: 1,
		border: "none",
		background: "transparent",
		padding: "10px 12px",
		fontSize: "14px",
		color: "var(--theme-text)",
		outline: "none",
		width: "100%",
	},
	chip: {
		flex: 1,
		display: "flex",
		alignItems: "center",
		gap: "6px",
		padding: "6px 8px",
		cursor: "pointer",
	},
	chipBadge: {
		display: "inline-flex",
		alignItems: "center",
		gap: "4px",
		padding: "4px 10px",
		borderRadius: "50px",
		fontSize: "13px",
		fontWeight: 500,
		background: "var(--theme-success-100)",
		color: "var(--theme-success-700)",
	},
	chipClear: {
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		width: "18px",
		height: "18px",
		borderRadius: "50%",
		border: "none",
		background: "rgba(255,255,255,0.25)",
		color: "var(--theme-success-700)",
		cursor: "pointer",
		padding: 0,
		marginLeft: "2px",
	},
	chevron: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		padding: "0 10px",
		cursor: "pointer",
		border: "none",
		background: "transparent",
		color: "var(--theme-dim)",
	},
	dropdown: {
		position: "absolute" as const,
		top: "100%",
		left: 0,
		right: 0,
		zIndex: 100,
		marginTop: "4px",
		border: "1px solid var(--theme-elevation-150)",
		borderRadius: "4px",
		background: "var(--theme-elevation-0)",
		boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
		maxHeight: "300px",
		overflowY: "auto" as const,
	},
	searchInput: {
		width: "100%",
		border: "none",
		borderBottom: "1px solid var(--theme-elevation-150)",
		background: "var(--theme-elevation-50)",
		padding: "8px 12px",
		fontSize: "13px",
		color: "var(--theme-text)",
		outline: "none",
		boxSizing: "border-box" as const,
	},
	groupHeader: {
		padding: "8px 12px 4px",
		fontSize: "11px",
		fontWeight: 600,
		textTransform: "uppercase" as const,
		color: "var(--theme-dim)",
		letterSpacing: "0.5px",
	},
	item: {
		padding: "8px 12px",
		fontSize: "13px",
		color: "var(--theme-text)",
		cursor: "pointer",
	},
	itemHighlighted: {
		background: "var(--theme-elevation-100)",
	},
	sectionItem: {
		paddingLeft: "24px",
	},
	loading: {
		padding: "12px",
		fontSize: "13px",
		color: "var(--theme-dim)",
		textAlign: "center" as const,
	},
	error: {
		padding: "12px",
		fontSize: "13px",
		color: "var(--theme-error-500, #e74c3c)",
		textAlign: "center" as const,
		cursor: "pointer",
	},
	description: {
		marginTop: "6px",
		fontSize: "12px",
		color: "rgb(154, 154, 154)",
	},
};
