/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'uk' | 'ru') | ('en' | 'uk' | 'ru')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'uk' | 'ru';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  blocks: (
    | HeroBlock
    | HeaderBlock
    | ProcessBlock
    | PricingBlock
    | PricingAltBlock
    | FeatureBlock
    | IntegrationBlock
    | TestimonialBlock
    | FaqBlock
    | CtaBlock
    | BlogBlock
    | FooterBlock
    | PartnershipBlock
  )[];
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  badge: {
    icon?: (number | null) | Media;
    text: string;
  };
  heading: string;
  subtitle: string;
  ctaForm: {
    inputPlaceholder: string;
    buttonText: string;
  };
  /**
   * Image of a person with transparent background, cropped above waist
   */
  personImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderBlock".
 */
export interface HeaderBlock {
  /**
   * Site logo for the navbar
   */
  logo?: (number | null) | Media;
  navLinks?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaText: string;
  ctaLink?: string | null;
  /**
   * Arrow icon for the CTA button
   */
  ctaArrowIcon?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'header';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlock".
 */
export interface ProcessBlock {
  badge: {
    icon?: (number | null) | Media;
    text: string;
  };
  heading: string;
  subtitle: string;
  tabs?:
    | {
        /**
         * Icon for the tab (16x16 recommended)
         */
        icon?: (number | null) | Media;
        /**
         * Icon for active state (16x16 recommended)
         */
        iconActive?: (number | null) | Media;
        title: string;
        badge: string;
        heading: string;
        description: string;
        buttonText: string;
        buttonLink?: string | null;
        /**
         * Visual representation for this tab
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'process';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  badge: {
    icon?: (number | null) | Media;
    text: string;
  };
  heading: string;
  subtitle: string;
  plan: {
    /**
     * Plan icon image
     */
    icon?: (number | null) | Media;
    name: string;
    description: string;
    price: string;
    period: string;
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    buttonText: string;
    buttonLink?: string | null;
  };
  /**
   * Testimonials will auto-scroll in columns (minimum 4 recommended for smooth animation)
   */
  testimonials?:
    | {
        quote: string;
        authorName: string;
        authorRole: string;
        authorImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingAltBlock".
 */
export interface PricingAltBlock {
  badge: {
    icon?: (number | null) | Media;
    text: string;
  };
  heading: string;
  subtitle: string;
  discountLabel?: string | null;
  plans?:
    | {
        name: string;
        badgeIcon?: (number | null) | Media;
        badgeText?: string | null;
        monthlyPrice: string;
        yearlyPrice?: string | null;
        period?: string | null;
        yearlyPeriod?: string | null;
        buttonText: string;
        buttonLink?: string | null;
        /**
         * Highlight this plan with gradient background
         */
        highlighted?: boolean | null;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricingAlt';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureBlock".
 */
export interface FeatureBlock {
  badge: {
    icon?: (number | null) | Media;
    text: string;
  };
  heading: string;
  subtitle: string;
  features?:
    | {
        /**
         * Feature icon
         */
        icon?: (number | null) | Media;
        heading: string;
        description: string;
        /**
         * Visual illustration for this feature
         */
        image?: (number | null) | Media;
        /**
         * Large cards span 6 columns (half width), small cards span 4 columns (third width) on desktop
         */
        layoutType: 'large' | 'small';
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'feature';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntegrationBlock".
 */
export interface IntegrationBlock {
  badge: {
    icon?: (number | null) | Media;
    text: string;
  };
  heading: string;
  /**
   * Main integration visualization image
   */
  mainImage?: (number | null) | Media;
  description: string;
  linkText: string;
  linkUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'integration';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock".
 */
export interface TestimonialBlock {
  badge: {
    icon?: (number | null) | Media;
    text: string;
  };
  heading: string;
  subtitle: string;
  testimonials?:
    | {
        /**
         * Optional logo for this testimonial
         */
        logo?: (number | null) | Media;
        quote: string;
        authorName: string;
        authorRole: string;
        /**
         * Author avatar image (48x48 recommended)
         */
        authorImage?: (number | null) | Media;
        /**
         * Card style - highlighted cards use purple background with white text
         */
        cardStyle: 'normal' | 'highlighted';
        /**
         * Grid span - double height cards span 2 rows (desktop only)
         */
        gridSpan: 'single' | 'double';
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  badge: {
    icon?: (number | null) | Media;
    text: string;
  };
  heading: string;
  subtitle: string;
  questions?:
    | {
        /**
         * Icon for this FAQ item (optional)
         */
        icon?: (number | null) | Media;
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  badge: {
    icon?: (number | null) | Media;
    text: string;
  };
  heading: string;
  subtitle: string;
  emailPlaceholder?: string | null;
  buttonText: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogBlock".
 */
export interface BlogBlock {
  badge: {
    icon?: (number | null) | Media;
    text: string;
  };
  heading: string;
  subtitle: string;
  posts?:
    | {
        /**
         * Blog post thumbnail image
         */
        image?: (number | null) | Media;
        title: string;
        description?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  explore: {
    heading: string;
    subtitle?: string | null;
    buttonText: string;
    buttonLink?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'blog';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterBlock".
 */
export interface FooterBlock {
  /**
   * Footer logo (light version recommended)
   */
  logo?: (number | null) | Media;
  menuGroups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletter: {
    heading: string;
    subtitle?: string | null;
    placeholder?: string | null;
    buttonText: string;
  };
  copyright?: string | null;
  socialLinks?:
    | {
        icon?: (number | null) | Media;
        href: string;
        /**
         * Accessible label (e.g. 'Twitter', 'Instagram')
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'footer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnershipBlock".
 */
export interface PartnershipBlock {
  badge: {
    icon?: (number | null) | Media;
    text: string;
  };
  heading: string;
  subtitle?: string | null;
  checklistItems: {
    text: string;
    /**
     * Highlight this item with brand accent color
     */
    highlighted?: boolean | null;
    id?: string | null;
  }[];
  buttonText: string;
  buttonLink?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnership';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        header?: T | HeaderBlockSelect<T>;
        process?: T | ProcessBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        pricingAlt?: T | PricingAltBlockSelect<T>;
        feature?: T | FeatureBlockSelect<T>;
        integration?: T | IntegrationBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        blog?: T | BlogBlockSelect<T>;
        footer?: T | FooterBlockSelect<T>;
        partnership?: T | PartnershipBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  ctaForm?:
    | T
    | {
        inputPlaceholder?: T;
        buttonText?: T;
      };
  personImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderBlock_select".
 */
export interface HeaderBlockSelect<T extends boolean = true> {
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  ctaText?: T;
  ctaLink?: T;
  ctaArrowIcon?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlock_select".
 */
export interface ProcessBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  tabs?:
    | T
    | {
        icon?: T;
        iconActive?: T;
        title?: T;
        badge?: T;
        heading?: T;
        description?: T;
        buttonText?: T;
        buttonLink?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  plan?:
    | T
    | {
        icon?: T;
        name?: T;
        description?: T;
        price?: T;
        period?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        buttonText?: T;
        buttonLink?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        authorName?: T;
        authorRole?: T;
        authorImage?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingAltBlock_select".
 */
export interface PricingAltBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  discountLabel?: T;
  plans?:
    | T
    | {
        name?: T;
        badgeIcon?: T;
        badgeText?: T;
        monthlyPrice?: T;
        yearlyPrice?: T;
        period?: T;
        yearlyPeriod?: T;
        buttonText?: T;
        buttonLink?: T;
        highlighted?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureBlock_select".
 */
export interface FeatureBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  features?:
    | T
    | {
        icon?: T;
        heading?: T;
        description?: T;
        image?: T;
        layoutType?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntegrationBlock_select".
 */
export interface IntegrationBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  mainImage?: T;
  description?: T;
  linkText?: T;
  linkUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock_select".
 */
export interface TestimonialBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  testimonials?:
    | T
    | {
        logo?: T;
        quote?: T;
        authorName?: T;
        authorRole?: T;
        authorImage?: T;
        cardStyle?: T;
        gridSpan?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  questions?:
    | T
    | {
        icon?: T;
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  emailPlaceholder?: T;
  buttonText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogBlock_select".
 */
export interface BlogBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  posts?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  explore?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterBlock_select".
 */
export interface FooterBlockSelect<T extends boolean = true> {
  logo?: T;
  menuGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  newsletter?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        placeholder?: T;
        buttonText?: T;
      };
  copyright?: T;
  socialLinks?:
    | T
    | {
        icon?: T;
        href?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnershipBlock_select".
 */
export interface PartnershipBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  checklistItems?:
    | T
    | {
        text?: T;
        highlighted?: T;
        id?: T;
      };
  buttonText?: T;
  buttonLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}