/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'uk' | 'ru') | ('en' | 'uk' | 'ru')[];
  globals: {
    header: Header;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
  };
  locale: 'en' | 'uk' | 'ru';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Короткий опис зображення для людей з вадами зору та пошукових систем
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Унікальна адреса сторінки в URL (автоматично форматується)
   */
  slug: string;
  /**
   * Додавайте та впорядковуйте блоки контенту на сторінці
   */
  blocks: (
    | HeroBlock
    | ProcessBlock
    | PricingBlock
    | PricingAltBlock
    | FeatureBlock
    | IntegrationBlock
    | TestimonialBlock
    | FaqBlock
    | CtaBlock
    | BlogBlock
    | FooterBlock
    | PartnershipBlock
    | GalleryBlock
    | ContactUsBlock
  )[];
  /**
   * Налаштування для пошукових систем (Google, тощо)
   */
  seo?: {
    /**
     * Заголовок сторінки для пошукових систем
     */
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  badge: {
    icon?: (number | null) | Media;
    /**
     * Короткий текст над заголовком секції
     */
    text: string;
  };
  /**
   * Головний заголовок секції
   */
  heading: string;
  /**
   * Короткий опис під заголовком
   */
  subtitle: string;
  ctaButton: {
    text: string;
    /**
     * Оберіть тип: власне посилання або перехід до секції на сторінці
     */
    linkType?: ('custom' | 'section') | null;
    /**
     * Введіть адресу сторінки, наприклад: https://example.com або /contact
     */
    url?: string | null;
    /**
     * Оберіть секцію, до якої буде прокручуватися сторінка
     */
    section?:
      | (
          | 'hero'
          | 'process'
          | 'pricing'
          | 'pricing-alt'
          | 'feature'
          | 'integration'
          | 'testimonial'
          | 'faq'
          | 'cta'
          | 'blog'
          | 'footer'
          | 'partnership'
          | 'gallery'
          | 'contact-us'
        )
      | null;
    /**
     * Якщо увімкнено — посилання відкриється в новій вкладці браузера
     */
    openInNewTab?: boolean | null;
  };
  /**
   * Фото людини з прозорим фоном, обрізане вище пояса
   */
  personImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlock".
 */
export interface ProcessBlock {
  badge: {
    icon?: (number | null) | Media;
    /**
     * Короткий текст над заголовком секції
     */
    text: string;
  };
  heading: string;
  subtitle: string;
  /**
   * Кроки процесу які відвідувач може перемикати
   */
  tabs?:
    | {
        /**
         * Невелика іконка (рекомендовано 16×16)
         */
        icon?: (number | null) | Media;
        /**
         * Іконка для активного стану (рекомендовано 16×16)
         */
        iconActive?: (number | null) | Media;
        title: string;
        /**
         * Наприклад: Крок 1, Крок 2
         */
        badge: string;
        heading: string;
        description: string;
        buttonText: string;
        /**
         * Оберіть тип: власне посилання або перехід до секції на сторінці
         */
        linkType?: ('custom' | 'section') | null;
        /**
         * Введіть адресу сторінки, наприклад: https://example.com або /contact
         */
        url?: string | null;
        /**
         * Оберіть секцію, до якої буде прокручуватися сторінка
         */
        section?:
          | (
              | 'hero'
              | 'process'
              | 'pricing'
              | 'pricing-alt'
              | 'feature'
              | 'integration'
              | 'testimonial'
              | 'faq'
              | 'cta'
              | 'blog'
              | 'footer'
              | 'partnership'
              | 'gallery'
              | 'contact-us'
            )
          | null;
        /**
         * Ілюстрація для цієї вкладки
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'process';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  badge: {
    icon?: (number | null) | Media;
    /**
     * Короткий текст над заголовком секції
     */
    text: string;
  };
  heading: string;
  subtitle: string;
  plan: {
    /**
     * Іконка для тарифного плану
     */
    icon?: (number | null) | Media;
    name: string;
    description: string;
    price: string;
    period: string;
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    buttonText: string;
    buttonLink?: string | null;
  };
  /**
   * Відгуки прокручуються автоматично (рекомендується мінімум 4 для плавної анімації)
   */
  testimonials?:
    | {
        quote: string;
        authorName: string;
        authorRole: string;
        authorImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingAltBlock".
 */
export interface PricingAltBlock {
  badge: {
    icon?: (number | null) | Media;
    /**
     * Короткий текст над заголовком секції
     */
    text: string;
  };
  heading: string;
  subtitle: string;
  discountLabel?: string | null;
  plans?:
    | {
        name: string;
        badgeIcon?: (number | null) | Media;
        badgeText?: string | null;
        monthlyPrice: string;
        yearlyPrice?: string | null;
        period?: string | null;
        yearlyPeriod?: string | null;
        buttonText: string;
        buttonLink?: string | null;
        /**
         * Виділити цей план градієнтним фоном
         */
        highlighted?: boolean | null;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricingAlt';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureBlock".
 */
export interface FeatureBlock {
  badge: {
    icon?: (number | null) | Media;
    /**
     * Короткий текст над заголовком секції
     */
    text: string;
  };
  heading: string;
  subtitle: string;
  features?:
    | {
        /**
         * Іконка для цієї можливості
         */
        icon?: (number | null) | Media;
        heading: string;
        description: string;
        /**
         * Ілюстрація для цієї можливості
         */
        image?: (number | null) | Media;
        /**
         * Великі картки займають половину ширини, малі — третину
         */
        layoutType: 'large' | 'small';
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'feature';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntegrationBlock".
 */
export interface IntegrationBlock {
  badge: {
    icon?: (number | null) | Media;
    /**
     * Короткий текст над заголовком секції
     */
    text: string;
  };
  heading: string;
  /**
   * Зображення для візуалізації інтеграцій
   */
  mainImage?: (number | null) | Media;
  description: string;
  linkText: string;
  linkUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'integration';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock".
 */
export interface TestimonialBlock {
  badge: {
    icon?: (number | null) | Media;
    /**
     * Короткий текст над заголовком секції
     */
    text: string;
  };
  heading: string;
  subtitle: string;
  testimonials?:
    | {
        /**
         * Логотип для цього відгуку (необовʼязково)
         */
        logo?: (number | null) | Media;
        quote: string;
        authorName: string;
        authorRole: string;
        /**
         * Аватар автора (рекомендовано 48×48)
         */
        authorImage?: (number | null) | Media;
        /**
         * Виділені картки мають фіолетовий фон та білий текст
         */
        cardStyle: 'normal' | 'highlighted';
        /**
         * Подвійні картки займають 2 рядки (тільки на десктопі)
         */
        gridSpan: 'single' | 'double';
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  badge: {
    icon?: (number | null) | Media;
    /**
     * Короткий текст над заголовком секції
     */
    text: string;
  };
  heading: string;
  subtitle: string;
  questions?:
    | {
        /**
         * Іконка для цього питання (необовʼязково)
         */
        icon?: (number | null) | Media;
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  badge: {
    icon?: (number | null) | Media;
    /**
     * Короткий текст над заголовком секції
     */
    text: string;
  };
  heading: string;
  subtitle: string;
  ctaButton: {
    text: string;
    /**
     * Оберіть тип: власне посилання або перехід до секції на сторінці
     */
    linkType?: ('custom' | 'section') | null;
    /**
     * Введіть адресу сторінки, наприклад: https://example.com або /contact
     */
    url?: string | null;
    /**
     * Оберіть секцію, до якої буде прокручуватися сторінка
     */
    section?:
      | (
          | 'hero'
          | 'process'
          | 'pricing'
          | 'pricing-alt'
          | 'feature'
          | 'integration'
          | 'testimonial'
          | 'faq'
          | 'cta'
          | 'blog'
          | 'footer'
          | 'partnership'
          | 'gallery'
          | 'contact-us'
        )
      | null;
    /**
     * Якщо увімкнено — посилання відкриється в новій вкладці браузера
     */
    openInNewTab?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogBlock".
 */
export interface BlogBlock {
  badge: {
    icon?: (number | null) | Media;
    /**
     * Короткий текст над заголовком секції
     */
    text: string;
  };
  heading: string;
  subtitle: string;
  posts?:
    | {
        /**
         * Мініатюра статті
         */
        image?: (number | null) | Media;
        title: string;
        description?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  explore: {
    heading: string;
    subtitle?: string | null;
    buttonText: string;
    buttonLink?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'blog';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterBlock".
 */
export interface FooterBlock {
  /**
   * Логотип у нижній частині сайту (рекомендується світла версія)
   */
  logo?: (number | null) | Media;
  /**
   * Колонки з посиланнями в нижній частині сайту
   */
  menuGroups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * Оберіть тип: власне посилання або перехід до секції на сторінці
               */
              linkType?: ('custom' | 'section') | null;
              /**
               * Введіть адресу сторінки, наприклад: https://example.com або /contact
               */
              url?: string | null;
              /**
               * Оберіть секцію, до якої буде прокручуватися сторінка
               */
              section?:
                | (
                    | 'hero'
                    | 'process'
                    | 'pricing'
                    | 'pricing-alt'
                    | 'feature'
                    | 'integration'
                    | 'testimonial'
                    | 'faq'
                    | 'cta'
                    | 'blog'
                    | 'footer'
                    | 'partnership'
                    | 'gallery'
                    | 'contact-us'
                  )
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletter: {
    heading: string;
    subtitle?: string | null;
    buttonText: string;
    /**
     * Оберіть тип: власне посилання або перехід до секції на сторінці
     */
    linkType?: ('custom' | 'section') | null;
    /**
     * Введіть адресу сторінки, наприклад: https://example.com або /contact
     */
    url?: string | null;
    /**
     * Оберіть секцію, до якої буде прокручуватися сторінка
     */
    section?:
      | (
          | 'hero'
          | 'process'
          | 'pricing'
          | 'pricing-alt'
          | 'feature'
          | 'integration'
          | 'testimonial'
          | 'faq'
          | 'cta'
          | 'blog'
          | 'footer'
          | 'partnership'
          | 'gallery'
          | 'contact-us'
        )
      | null;
  };
  copyright?: string | null;
  /**
   * Посилання на соціальні мережі (іконки внизу сторінки)
   */
  socialLinks?:
    | {
        icon?: (number | null) | Media;
        href: string;
        /**
         * Наприклад: Instagram, Telegram, Facebook
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'footer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnershipBlock".
 */
export interface PartnershipBlock {
  badge: {
    icon?: (number | null) | Media;
    /**
     * Короткий текст над заголовком секції
     */
    text: string;
  };
  heading: string;
  subtitle?: string | null;
  checklistItems: {
    text: string;
    /**
     * Виділити цей пункт акцентним кольором
     */
    highlighted?: boolean | null;
    id?: string | null;
  }[];
  buttonText: string;
  buttonLink?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnership';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  badge: {
    icon?: (number | null) | Media;
    /**
     * Короткий текст над заголовком секції
     */
    text: string;
  };
  heading: string;
  subtitle: string;
  images?:
    | {
        image: number | Media;
        /**
         * Короткий опис для людей з вадами зору
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactUsBlock".
 */
export interface ContactUsBlock {
  badge: {
    icon?: (number | null) | Media;
    /**
     * Короткий текст над заголовком секції
     */
    text: string;
  };
  heading: string;
  subtitle: string;
  cardHeading: string;
  cardDescription: string;
  contactItems?:
    | {
        type: 'email' | 'telegram' | 'phone';
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Тексти для полів контактної форми
   */
  formFields: {
    nameLabel: string;
    namePlaceholder: string;
    emailLabel: string;
    emailPlaceholder: string;
    phoneLabel: string;
    phonePlaceholder: string;
    companyLabel: string;
    companyPlaceholder: string;
    messageLabel: string;
    messagePlaceholder: string;
  };
  buttonText: string;
  /**
   * Фонове зображення для секції (рекомендовано: мʼякий градієнт або фото природи)
   */
  backgroundImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactUs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        process?: T | ProcessBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        pricingAlt?: T | PricingAltBlockSelect<T>;
        feature?: T | FeatureBlockSelect<T>;
        integration?: T | IntegrationBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        blog?: T | BlogBlockSelect<T>;
        footer?: T | FooterBlockSelect<T>;
        partnership?: T | PartnershipBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        contactUs?: T | ContactUsBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  ctaButton?:
    | T
    | {
        text?: T;
        linkType?: T;
        url?: T;
        section?: T;
        openInNewTab?: T;
      };
  personImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlock_select".
 */
export interface ProcessBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  tabs?:
    | T
    | {
        icon?: T;
        iconActive?: T;
        title?: T;
        badge?: T;
        heading?: T;
        description?: T;
        buttonText?: T;
        linkType?: T;
        url?: T;
        section?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  plan?:
    | T
    | {
        icon?: T;
        name?: T;
        description?: T;
        price?: T;
        period?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        buttonText?: T;
        buttonLink?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        authorName?: T;
        authorRole?: T;
        authorImage?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingAltBlock_select".
 */
export interface PricingAltBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  discountLabel?: T;
  plans?:
    | T
    | {
        name?: T;
        badgeIcon?: T;
        badgeText?: T;
        monthlyPrice?: T;
        yearlyPrice?: T;
        period?: T;
        yearlyPeriod?: T;
        buttonText?: T;
        buttonLink?: T;
        highlighted?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureBlock_select".
 */
export interface FeatureBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  features?:
    | T
    | {
        icon?: T;
        heading?: T;
        description?: T;
        image?: T;
        layoutType?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntegrationBlock_select".
 */
export interface IntegrationBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  mainImage?: T;
  description?: T;
  linkText?: T;
  linkUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock_select".
 */
export interface TestimonialBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  testimonials?:
    | T
    | {
        logo?: T;
        quote?: T;
        authorName?: T;
        authorRole?: T;
        authorImage?: T;
        cardStyle?: T;
        gridSpan?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  questions?:
    | T
    | {
        icon?: T;
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  ctaButton?:
    | T
    | {
        text?: T;
        linkType?: T;
        url?: T;
        section?: T;
        openInNewTab?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogBlock_select".
 */
export interface BlogBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  posts?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  explore?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterBlock_select".
 */
export interface FooterBlockSelect<T extends boolean = true> {
  logo?: T;
  menuGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              linkType?: T;
              url?: T;
              section?: T;
              id?: T;
            };
        id?: T;
      };
  newsletter?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        buttonText?: T;
        linkType?: T;
        url?: T;
        section?: T;
      };
  copyright?: T;
  socialLinks?:
    | T
    | {
        icon?: T;
        href?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnershipBlock_select".
 */
export interface PartnershipBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  checklistItems?:
    | T
    | {
        text?: T;
        highlighted?: T;
        id?: T;
      };
  buttonText?: T;
  buttonLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactUsBlock_select".
 */
export interface ContactUsBlockSelect<T extends boolean = true> {
  badge?:
    | T
    | {
        icon?: T;
        text?: T;
      };
  heading?: T;
  subtitle?: T;
  cardHeading?: T;
  cardDescription?: T;
  contactItems?:
    | T
    | {
        type?: T;
        value?: T;
        id?: T;
      };
  formFields?:
    | T
    | {
        nameLabel?: T;
        namePlaceholder?: T;
        emailLabel?: T;
        emailPlaceholder?: T;
        phoneLabel?: T;
        phonePlaceholder?: T;
        companyLabel?: T;
        companyPlaceholder?: T;
        messageLabel?: T;
        messagePlaceholder?: T;
      };
  buttonText?: T;
  backgroundImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Логотип який відображається у верхній частині сайту
   */
  logo?: (number | null) | Media;
  /**
   * Пункти меню у верхній частині сайту (від 1 до 8)
   */
  navLinks?:
    | {
        /**
         * Текст який бачить відвідувач
         */
        label: string;
        /**
         * Оберіть тип: власне посилання або перехід до секції на сторінці
         */
        linkType?: ('custom' | 'section') | null;
        /**
         * Введіть адресу сторінки, наприклад: https://example.com або /contact
         */
        url?: string | null;
        /**
         * Оберіть секцію, до якої буде прокручуватися сторінка
         */
        section?:
          | (
              | 'hero'
              | 'process'
              | 'pricing'
              | 'pricing-alt'
              | 'feature'
              | 'integration'
              | 'testimonial'
              | 'faq'
              | 'cta'
              | 'blog'
              | 'footer'
              | 'partnership'
              | 'gallery'
              | 'contact-us'
            )
          | null;
        /**
         * Випадаючий список під цим пунктом (необовʼязково)
         */
        children?:
          | {
              /**
               * Текст який бачить відвідувач
               */
              label: string;
              /**
               * Оберіть тип: власне посилання або перехід до секції на сторінці
               */
              linkType?: ('custom' | 'section') | null;
              /**
               * Введіть адресу сторінки, наприклад: https://example.com або /contact
               */
              url?: string | null;
              /**
               * Оберіть секцію, до якої буде прокручуватися сторінка
               */
              section?:
                | (
                    | 'hero'
                    | 'process'
                    | 'pricing'
                    | 'pricing-alt'
                    | 'feature'
                    | 'integration'
                    | 'testimonial'
                    | 'faq'
                    | 'cta'
                    | 'blog'
                    | 'footer'
                    | 'partnership'
                    | 'gallery'
                    | 'contact-us'
                  )
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Текст на головній кнопці у шапці
   */
  ctaText: string;
  /**
   * Оберіть тип: власне посилання або перехід до секції на сторінці
   */
  linkType?: ('custom' | 'section') | null;
  /**
   * Введіть адресу сторінки, наприклад: https://example.com або /contact
   */
  url?: string | null;
  /**
   * Оберіть секцію, до якої буде прокручуватися сторінка
   */
  section?:
    | (
        | 'hero'
        | 'process'
        | 'pricing'
        | 'pricing-alt'
        | 'feature'
        | 'integration'
        | 'testimonial'
        | 'faq'
        | 'cta'
        | 'blog'
        | 'footer'
        | 'partnership'
        | 'gallery'
        | 'contact-us'
      )
    | null;
  /**
   * Іконка стрілки біля тексту кнопки (необовʼязково)
   */
  ctaArrowIcon?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        url?: T;
        section?: T;
        children?:
          | T
          | {
              label?: T;
              linkType?: T;
              url?: T;
              section?: T;
              id?: T;
            };
        id?: T;
      };
  ctaText?: T;
  linkType?: T;
  url?: T;
  section?: T;
  ctaArrowIcon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}