import type { Block } from "payload";

export const PricingAltBlock: Block = {
	slug: "pricingAlt",
	interfaceName: "PricingAltBlock",
	labels: {
		singular: "Ціни (альтернативний)",
		plural: "Ціни (альтернативні)",
	},
	fields: [
		{
			name: "badge",
			type: "group",
			label: "Бейдж",
			fields: [
				{
					name: "icon",
					type: "upload",
					label: "Іконка бейджу",
					relationTo: "media",
					required: false,
				},
				{
					name: "text",
					type: "text",
					label: "Текст бейджу",
					required: true,
					localized: true,
					defaultValue: "Your Investment",
					admin: {
						description: "Короткий текст над заголовком секції",
					},
				},
			],
		},
		{
			name: "heading",
			type: "text",
			label: "Заголовок",
			required: true,
			localized: true,
			defaultValue: "Simple, transparent pricing",
		},
		{
			name: "subtitle",
			type: "textarea",
			label: "Підзаголовок",
			required: true,
			localized: true,
			defaultValue:
				"Choose the path that resonates with your journey. No hidden costs, no surprises — just honest pricing for genuine transformation.",
		},
		{
			name: "discountLabel",
			type: "text",
			label: "Текст знижки",
			required: false,
			localized: true,
			defaultValue: "Save 15%",
		},
		{
			name: "plans",
			type: "array",
			label: "Тарифні плани",
			minRows: 1,
			maxRows: 4,
			defaultValue: [
				{
					name: "Seeker Path",
					badgeText: "Most Popular",
					monthlyPrice: "$33",
					yearlyPrice: "$28",
					period: "/monthly",
					yearlyPeriod: "/yearly",
					buttonText: "Begin Now",
					highlighted: false,
					features: [
						{ text: "Guided meditation library" },
						{ text: "Weekly group sessions" },
						{ text: "Personal practice tracker" },
						{ text: "Community access" },
					],
				},
				{
					name: "Deep Journey",
					badgeText: "For Committed Seekers",
					monthlyPrice: "$67",
					yearlyPrice: "$57",
					period: "/monthly",
					yearlyPeriod: "/yearly",
					buttonText: "Begin Now",
					highlighted: true,
					features: [
						{ text: "Everything in Seeker Path" },
						{ text: "1-on-1 mentorship sessions" },
						{ text: "Advanced breathwork practices" },
						{ text: "Personalized transformation plan" },
						{ text: "Priority support" },
						{ text: "Exclusive retreats access" },
					],
				},
			],
			fields: [
				{
					name: "name",
					type: "text",
					label: "Назва",
					required: true,
					localized: true,
				},
				{
					name: "badgeIcon",
					type: "upload",
					label: "Іконка бейджу",
					relationTo: "media",
					required: false,
				},
				{
					name: "badgeText",
					type: "text",
					label: "Текст бейджу",
					required: false,
					localized: true,
				},
				{
					name: "monthlyPrice",
					type: "text",
					label: "Ціна за місяць",
					required: true,
					localized: true,
				},
				{
					name: "yearlyPrice",
					type: "text",
					label: "Ціна за рік",
					required: false,
					localized: true,
				},
				{
					name: "period",
					type: "text",
					label: "Період (місяць)",
					required: false,
					localized: true,
					defaultValue: "/monthly",
				},
				{
					name: "yearlyPeriod",
					type: "text",
					label: "Період (рік)",
					required: false,
					localized: true,
					defaultValue: "/yearly",
				},
				{
					name: "buttonText",
					type: "text",
					label: "Текст кнопки",
					required: true,
					localized: true,
					defaultValue: "Begin Now",
				},
				{
					name: "buttonLink",
					type: "text",
					label: "Посилання кнопки",
					required: false,
				},
				{
					name: "highlighted",
					type: "checkbox",
					label: "Виділений план",
					defaultValue: false,
					admin: {
						description:
							"Виділити цей план градієнтним фоном",
					},
				},
				{
					name: "features",
					type: "array",
					label: "Переваги",
					minRows: 1,
					maxRows: 10,
					fields: [
						{
							name: "text",
							type: "text",
							label: "Текст переваги",
							required: true,
							localized: true,
						},
					],
				},
			],
		},
	],
};
